### ISSUE TITLE
Various TODO's in the code

### ISSUE THREAD

**Issue by jgallowa07** [matsengrp/multidms#153]
I have a small litany of things I noticed during the last few PR's that I didn't want to get side-tracked with at the time. Here is the list of small things we could do to cleanup the source code and interface a little.

- [x] Rename "huber_scale_huber" parameter -> "huber_scale"
- [x] Get[ this ](https://github.com/matsengrp/multidms/blob/79dc61a989387b6a070be9e8f65afc24b1903c08/multidms/data.py#L328)to follow the -1 heuristic for using all CPU's
- [x] we should probably remove the get_ prefix from get_mutations_df and get_variants_df . get should only be for getter/setter operations
- [x] we should add method to output wide version of mutations df. This is really useful for many of the plots we make for the manuscript
- [x] make sure for all plotting functions (that it's appropriate) we have the R^2 option to show coefficient of determination.
- [x] remove the ipywidgets dependency and the fancy progress bars. They're annoying and unnecessary. 
- [x] rename the `ModelCollection.fit_models` attribute -> `ModelCollection.models_df`
- [x] We could allow for singletons in the params dict passed to `fit_models`. It would make for a nicer interface
- [x] Let's do the kwargs thing [here](https://github.com/matsengrp/multidms/blob/79dc61a989387b6a070be9e8f65afc24b1903c08/multidms/model_collection.py#L58)
- [x] Make the epistatic and activation function arguments to model a string instead of the function definition.
- [x] Allow output of Model.get_mutations_df() to output either wide, or tall formats.
- [x] Print more useful error message when fits fail in `fit_models` call
- [x] Use pytest fixtures to speed things up and make global test inputs more consistent
- [x] Make method for printing convergence trajectory for models.
- [x] Let's make sure condition names match a certain pattern, like that there's no "." in the condition name. That would clean up a lot of the altair plotting code.

**Comment by jgallowa07** [comment]
Many of these could be useful - but very low priority. But many might be outdated by the time we implement this new interface.
